# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
# - name: "DucklingHTTPExtractor"
#   # url of the running duckling server
#   url: "http://localhost:8000"
#   # dimensions to extract
#   dimensions: ["time", "number", "amount-of-money", "distance"]
#   # allows you to configure the locale, by default the language is
#   # used
#   locale: "de_DE"
#   # if not set the default timezone of Duckling is going to be used
#   # needed to calculate dates from relative expressions like "tomorrow"
#   timezone: "Asia/India"
#   # Timeout for receiving response from http url of the running duckling server
#   # if not set the default timeout of duckling http url is set to 3 seconds.
#   timeout : 3
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
